export const homeMetadata = {
    title: "Welcome / Asfartrip.com",
    description: "Generated by create SWD97",
};

export const rootLayoutMetadata = {
    title: {
        template: "%s / Asfartrip.com",
        default: "Welcome / Asfartrip.com",
    },
    description: "Generated by create SWD97",
};

// _libs/metadata.js
export function generateMetadataObj({
    title,
    description,
    url,
    locale = "en",
    image,
}) {
    const ogImage = image ?? "https://www.asfartrip.com/og-image.jpg";

    return {
        title,
        description,
        keywords:
            "flight tickets, hotel bookings, car rentals, travel insurance, holiday packages, OTA, AsfarTrip",
        canonical: url,
        robots: "index, follow",

        openGraph: {
            title,
            description,
            url,
            type: "website",
            siteName: "AsfarTrip",
            images: [{ url: ogImage, width: 1200, height: 630, alt: title }],
            locale: locale === "ar" ? "ar_AE" : "en_US",
        },

        twitter: {
            card: "summary_large_image",
            title,
            description,
            images: [ogImage],
            site: "@AsfarTrip",
        },

        google: { title, description, image: ogImage },

        social: {
            facebook: {
                "og:title": title,
                "og:description": description,
                "og:image": ogImage,
                "og:url": url,
                "og:type": "website",
            },
            instagram: {
                "og:title": title,
                "og:description": description,
                "og:image": ogImage,
                "og:url": url,
            },
            tiktok: {
                "og:title": title,
                "og:description": description,
                "og:image": ogImage,
                "og:url": url,
            },
        },
    };
}
