import { Metadata } from "next";

export const homeMetadata = {
  title: "Welcome / Asfartrip.com",
  description: "Generated by create SWD97",
};

export const rootLayoutMetadata = {
  title: {
    template: "%s / Asfartrip.com",
    default: "Welcome / Asfartrip.com",
  },
  description: "Generated by create SWD97",
};
