/**
 * Continents and their top 10 cities for hotel recommendations
 */
export const CONTINENTS = [
    {
        id: "europe",
        name: "Europe",
        emoji: "🇪🇺",
        cities: [
            { name: "Paris", country: "FR" },
            { name: "London", country: "GB" },
            { name: "Rome", country: "IT" },
            { name: "Barcelona", country: "ES" },
            { name: "Amsterdam", country: "NL" },
            // { name: "Venice", country: "IT" },
            { name: "Istanbul", country: "TR" },
            { name: "Prague", country: "CZ" },
            { name: "Vienna", country: "AT" },
            // { name: "Munich", country: "DE" },
        ],
    },
    {
        id: "asia",
        name: "Asia",
        emoji: "🌏",
        cities: [
            { name: "Dubai", country: "AE" },
            { name: "Bangkok", country: "TH" },
            { name: "Tokyo", country: "JP" },
            { name: "Singapore", country: "SG" },
            { name: "Kuala Lumpur", country: "MY" },
            { name: "Hong Kong", country: "HK" },
            { name: "Seoul", country: "KR" },
            // { name: "Bali", country: "ID" },
            { name: "Shanghai", country: "CN" },
            { name: "Mumbai", country: "IN" },
        ],
    },
    {
        id: "africa",
        name: "Africa",
        emoji: "🌍",
        cities: [
            // { name: "cape_town", country: "ZA" },
            { name: "marrakesh", country: "MA" },
            { name: "Cairo", country: "EG" },
            { name: "Sharm El Sheikh", country: "EG" },
            { name: "Hurghada", country: "EG" },
            { name: "Tunis", country: "TN" },
            { name: "Nairobi", country: "KE" },
            // { name: "zanzibar", country: "TZ" },
            { name: "Accra", country: "GH" },
            // { name: "Addis Ababa", country: "ET" },
        ],
    },
    {
        id: "north_america",
        name: "North America",
        emoji: "🌎",
        cities: [
            { name: "New York", country: "US" },
            { name: "Las Vegas", country: "US" },
            { name: "Los Angeles", country: "US" },
            { name: "Orlando", country: "US" },
            { name: "Miami", country: "US" },
            { name: "San Francisco", country: "US" },
            { name: "Toronto", country: "CA" },
            { name: "Vancouver", country: "CA" },
            // { name: "Mexico City", country: "MX" },
            // { name: "Cancun", country: "MX" },
        ],
    },
    {
        id: "south_america",
        name: "South America",
        emoji: "🌎",
        cities: [
            // { name: "Rio de Janeiro", country: "BR" },
            { name: "Buenos Aires", country: "AR" },
            { name: "São Paulo", country: "BR" },
            // { name: "Lima", country: "PE" },
            // { name: "Santiago", country: "CL" },
            // { name: "Cartagena", country: "CO" },
            { name: "Bogotá", country: "CO" },
            // { name: "Montevideo", country: "UY" },
            // { name: "Cusco", country: "PE" },
            // { name: "Quito", country: "EC" },
        ],
    },
    {
        id: "oceania",
        name: "Australia & Oceania",
        emoji: "🌏",
        cities: [
            { name: "Sydney", country: "AU" },
            { name: "Melbourne", country: "AU" },
            // { name: "Brisbane", country: "AU" },
            // { name: "Gold Coast", country: "AU" },
            { name: "Perth", country: "AU" },
            { name: "Auckland", country: "NZ" },
            // { name: "Queenstown", country: "NZ" },
            // { name: "Wellington", country: "NZ" },
            // { name: "Nadi", country: "FJ" },
            // { name: "Hobart", country: "AU" },
        ],
    },
];
